### ISSUE TITLE
Regenerating cache file repeatedly with jekyll serve

### ISSUE THREAD

**Issue by gungorbudak** [valerijaspasojevic/jekyll-compress-images#5]
Hi, I'm using latest `master` branch code for the plugin, `jekyll` version `3.7.4`, `ruby` version `ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]`

`config.xml` options
```
compress_images:
  images_path: "uploads/*.{gif,png,jpg,jpeg,svg}"
  
imageoptim:
  svgo: false
  verbose: false
```

Using `jekyll serve`, when there is a change in any other file and after `jekyll serve` attempts to regenerate that file, it starts keep regenerating cache file and never stops.

I see endless messages like below.

```
      Regenerating: 1 file(s) changed at 2019-04-25 16:54:20
                    _compress_images_cache.yml
                    ...done in 0.566471 seconds.
                    
      Regenerating: 1 file(s) changed at 2019-04-25 16:54:21
                    _compress_images_cache.yml
                    ...done in 0.547225 seconds.
                    
      Regenerating: 1 file(s) changed at 2019-04-25 16:54:22
                    _compress_images_cache.yml
```
